User.create!(email: "ryou.ono@gmail.com", password:"ryou.ono", admin: true)
User.create!(email: "oda.nobunaga@gmail.com", password:"oda.nobunaga")
User.create!(email: "toyotomi.hideyosi@gmail.com", password:"toyotomi.hideyosi")
User.create!(email: "tokugawa.ieyasu@gmail.com", password:"tokugawa.ieyasu")
User.create!(email: "houzyo.uziyasu@gmail.com", password:"houzyo.uziyasu")
